root = "." # The root directory of the project
tmp_dir = "tmp" # The temporary directory of the project where air will store its temporary files

[build] # The build configuration
  bin = "main" # The name of the binary file to be generated after building the project
  cmd = "go build -o {{.Output}} {{.Input}}" # The command to build the project
  exclude = ["tmp/*", "client/*"] # Specifies which dirs to exclude from monitoring
  include = ["**/*.go"] # Specifies the file patterns to monitor
  ignore = ["tmp/*"] # Specifies the files or dirs to be ignored when triggering a build